# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(db_column='ID_PROYECTO', primary_key=True, serialize=False)),
                ('sigla_proy', models.CharField(blank=True, db_column='SIGLA_PROY', max_length=20, null=True)),
                ('anio_proy', models.CharField(blank=True, db_column='ANIO_PROY', max_length=4, null=True)),
                ('des_proy', models.CharField(blank=True, db_column='DES_PROY', max_length=60, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'PROYECTO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProyectoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Proyecto')),
            ],
            options={
                'db_table': 'PROYECTO_SISTEMA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id_sistema', models.AutoField(db_column='ID_SISTEMA', primary_key=True, serialize=False)),
                ('des_sist', models.CharField(blank=True, db_column='DES_SIST', max_length=100, null=True)),
                ('nom_sist', models.CharField(blank=True, db_column='NOM_SIST', max_length=50, null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('proyectos', models.ManyToManyField(through='seguridad.ProyectoSistema', to='seguridad.Proyecto')),
            ],
            options={
                'db_table': 'SISTEMA',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_USUARIO', primary_key=True, serialize=False)),
                ('dni', models.CharField(db_column='DNI', max_length=8)),
                ('ape_pat_per', models.CharField(blank=True, db_column='APE_PAT_PER', max_length=35, null=True)),
                ('ape_mat_per', models.CharField(blank=True, db_column='APE_MAT_PER', max_length=35, null=True)),
                ('nom_emp_per', models.CharField(blank=True, db_column='NOM_EMP_PER', max_length=35, null=True)),
                ('fec_nac_per', models.DateTimeField(blank=True, db_column='FEC_NAC_PER', null=True)),
                ('email_insti', models.CharField(blank=True, db_column='EMAIL_INSTI', max_length=50, null=True)),
                ('sex_emp_per', models.CharField(blank=True, db_column='SEX_EMP_PER', max_length=1, null=True)),
                ('usuario', models.CharField(blank=True, db_column='USUARIO', max_length=20, null=True)),
            ],
            options={
                'db_table': 'USUARIO',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioProyectoSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyectosistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.ProyectoSistema')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Usuario')),
            ],
            options={
                'db_table': 'USUARIO_PROYECTO_SISTEMA',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='proyectos_sistemas',
            field=models.ManyToManyField(through='seguridad.UsuarioProyectoSistema', to='seguridad.ProyectoSistema'),
        ),
        migrations.AddField(
            model_name='proyectosistema',
            name='id_sistema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguridad.Sistema'),
        ),
    ]
