# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='proyectosistema',
            unique_together=set([('id_proyecto', 'id_sistema')]),
        ),
        migrations.AlterUniqueTogether(
            name='usuarioproyectosistema',
            unique_together=set([('id_usuario', 'id_proyectosistema')]),
        ),
    ]
